- name: Download and install GitLab repository script
  shell: |
    curl -s https://packages.gitlab.com/install/repositories/gitlab/glab/script.deb.sh | bash
  args:
    creates: /etc/apt/sources.list.d/gitlab_glab.list
    
- name: Install glab
  apt:
    name: glab
    state: present
    update_cache: yes