---
- name: Install Software for Worker
  hosts: workers
  become: true

  tasks: 
    - name: Update Catch
      import_tasks: ./tasks/updare-cach.yaml

    - name: Install Portainer
      import_tasks: ./tasks/task-Portainer.yaml

    - name: Install Portainer
      import_tasks: ./tasks/task-Portainer.yaml

    - name: Install Portainer
      import_tasks: ./tasks/task-Portainer.yaml
      
    - name: Install Portainer
      import_tasks: ./tasks/task-Portainer.yaml