---
- name: Install Software for Worker
  hosts: aworkers
  become: true

  tasks: 
  - name: nstall OMZ
    import_tasks: ./tasks/task-OMZ-Portainer.yaml

  - name: Install Portainer
    import_tasks: ./tasks/task-Portainer.yaml